# Generated by Django 3.1 on 2019-09-21 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('good_flow_app', '0006_drop_field_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testtable',
            name='field',
        ),
    ]
