# Generated by Django 3.1 on 2019-09-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_flow_app', '0007_drop_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtable',
            name='field',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
