# Generated by Django 3.1 on 2019-09-22 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_flow_app', '0009_drop_field_with_check_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtable',
            name='field',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='good_flow_app.RelatedTestTable'
            ),
        ),
    ]
