# Generated by Django 3.1 on 2019-09-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_flow_app', '0011_drop_field_with_foreign_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtable',
            name='field',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
