# Generated by Django 3.1 on 2019-09-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_flow_app', '0013_drop_field_with_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtable',
            name='field',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
