# Generated by Django 3.1 on 2019-09-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_flow_app', '0015_drop_field_with_index'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='testtable',
            constraint=models.CheckConstraint(check=models.Q(test_field__gt=0), name='test_check_constraint'),
        ),
    ]
