# Generated by Django 3.1 on 2019-09-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_flow_app', '0017_drop_check_constraint'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='testtable',
            constraint=models.UniqueConstraint(fields=('test_field',), name='test_uniq_constraint'),
        ),
    ]
