# Generated by Django 3.1 on 2019-09-22 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('good_flow_app', '0020_add_unique_constraint_with_condition'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='testtable',
            name='test_uniq_constraint',
        ),
    ]
