# Generated by Django 3.1 on 2019-09-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_flow_app', '0021_drop_unique_constraint_with_condition'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='testtable',
            index=models.Index(fields=['test_field_int'], name='test_index'),
        ),
    ]
