# Generated by Django 3.1 on 2019-09-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_flow_app', '0023_drop_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='testtable',
            index=models.Index(condition=models.Q(test_field__isnull=False), fields=['test_field'], name='test_index'),
        ),
    ]
