# Generated by Django 3.0a1 on 2019-10-14 19:49

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_flow_app', '0047_drop_spgist_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='testtable',
            index=django.contrib.postgres.indexes.SpGistIndex(
                condition=models.Q(test_field_str__isnull=False),
                fields=['test_field_str'],
                name='test_index',
            ),
        ),
    ]
