# Generated by Django 4.2.20 on 2025-03-16 16:58

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('good_flow_app', '0049_drop_spgist_index_with_condition'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='testtable',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('test_field_int',), name='test_uniq_constraint_deferred'),
        ),
        migrations.AddConstraint(
            model_name='testtable',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['IMMEDIATE'], fields=('test_field_str',), name='test_uniq_constraint_immediate'),
        ),
    ]
