# Generated by Django 4.2.20 on 2025-03-16 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('good_flow_app', '0050_add_unique_constraint_deferrable'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='testtable',
            name='test_uniq_constraint_deferred',
        ),
        migrations.RemoveConstraint(
            model_name='testtable',
            name='test_uniq_constraint_immediate',
        ),
    ]
