# Generated by Django 3.1 on 2019-09-21 20:09

import django.contrib.postgres.search
from django.db import migrations, models


def insert_objects(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    TestTable = apps.get_model('good_flow_app_concurrently', 'TestTable')
    TestTable.objects.using(db_alias).create(test_field_int=1)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedTestTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_field_int', models.IntegerField()),
                ('test_field_str', models.CharField(max_length=10)),
                ('test_field_tsv', django.contrib.postgres.search.SearchVectorField()),
            ],
        ),
        migrations.RunPython(insert_objects, migrations.RunPython.noop),
    ]
