# Generated by Django 3.0a1 on 2019-12-10 21:48
from django.contrib.postgres.operations import RemoveIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):

    atomic = False
    dependencies = [
        ('good_flow_app_concurrently', '0002_auto_20191210_2147'),
    ]

    operations = [
        RemoveIndexConcurrently(
            model_name='testtable',
            name='good_flow_a_test_fi_0b7e6f_idx',
        ),
    ]
