from .settings import *  # noqa: F401, F403

INSTALLED_APPS += [  # noqa: F405
    'tests.apps.good_flow_alter_table_with_same_db_table',
    'tests.apps.good_flow_app',
    'tests.apps.good_flow_app_concurrently',
    'tests.apps.good_flow_add_column_generated_virtual_app',
    'tests.apps.good_flow_db_on_delete_app',
    'tests.apps.bad_rollback_flow_drop_column_with_notnull_default_app',
    'tests.apps.bad_rollback_flow_drop_column_with_notnull_app',
    'tests.apps.bad_rollback_flow_change_char_type_that_safe_app',
    'tests.apps.bad_flow_add_column_generated_stored_app',
    'tests.apps.bad_flow_add_column_with_default_app',
    'tests.apps.bad_flow_add_column_with_notnull_default_app',
    'tests.apps.bad_flow_add_column_with_notnull_app',
    'tests.apps.bad_flow_change_char_type_that_unsafe_app',
    'tests.apps.good_flow_drop_table_with_constraints',
    'tests.apps.good_flow_drop_column_with_constraints',
    'tests.apps.decimal_to_float_app',
    'tests.apps.rename_and_drop_app',
    'tests.apps.idempotency_create_table_app',
    'tests.apps.idempotency_add_column_app',
    'tests.apps.idempotency_add_column_foreign_key_app',
    'tests.apps.idempotency_add_column_one_to_one_app',
    'tests.apps.idempotency_set_not_null_app',
    'tests.apps.idempotency_add_check_app',
    'tests.apps.idempotency_add_foreign_key_app',
    'tests.apps.idempotency_add_one_to_one_app',
    'tests.apps.idempotency_add_index_app',
    'tests.apps.idempotency_add_index_meta_app',
    'tests.apps.idempotency_add_unique_app',
    'tests.apps.idempotency_add_unique_meta_app',
    'tests.apps.idempotency_add_primary_key_app',
    'tests.apps.idempotency_add_auto_field_app',
]
