# Generated by Django 3.1 on 2021-12-30 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('good_flow_alter_table_with_same_db_table', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestTable',
            new_name='TestTableRenamed',
        ),
    ]
