# Generated by Django 3.1 on 2019-09-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_flow_add_column_with_notnull_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtable',
            name='field',
            field=models.IntegerField(),
        ),
    ]
