from django.db import connection

import pytest

from django_zero_downtime_migrations.backends.postgres.schema import DatabaseSchemaEditorMixin
from tests import skip_for_default_django_backend

pytestmark = [skip_for_default_django_backend, pytest.mark.django_db]


def quote(name: str) -> str:
    """Quote an identifier the way a `db_table` that is already quoted reaches a template.

    `quote_name` does not double a quote inside a bare name, thus an already quoted
    `db_table` is the only way a name with a quote or a schema in it gets that far.
    """
    return '"%s"' % name.replace('"', '""')


def probe(sql: str, **parts: str) -> bool:
    # `execute` interpolates the already quoted values that `statement.parts` carries
    with connection.cursor() as cursor:
        cursor.execute(sql % parts)
        return cursor.fetchone() is not None


def create_table(table: str, column: str, constraint: str, index: str, schema: str = ""):
    prefix = f"{quote(schema)}." if schema else ""
    with connection.cursor() as cursor:
        if schema:
            cursor.execute(f"CREATE SCHEMA {quote(schema)}")
        cursor.execute(
            f"CREATE TABLE {prefix}{quote(table)} ("
            f"{quote(column)} integer GENERATED BY DEFAULT AS IDENTITY, "
            f"CONSTRAINT {quote(constraint)} UNIQUE ({quote(column)})"
            f")"
        )
        cursor.execute(f"CREATE INDEX {quote(index)} ON {prefix}{quote(table)} ({quote(column)})")


def assert_all_conditions(table: str, column: str, constraint: str, index: str, found: bool):
    editor = DatabaseSchemaEditorMixin
    assert probe(editor._sql_table_exists, table=quote(table)) is found
    assert probe(editor._sql_new_table_exists, new_table=quote(table)) is found
    assert probe(editor._sql_column_exists, table=quote(table), column=quote(column)) is found
    assert probe(editor._sql_new_column_exists, table=quote(table), new_column=quote(column)) is found
    assert probe(editor._sql_identity_exists, table=quote(table), column=quote(column)) is found
    assert probe(editor._sql_constraint_exists, table=quote(table), name=quote(constraint)) is found
    assert probe(editor._sql_index_exists, name=quote(index)) is found
    assert probe(editor._sql_index_valid, table=quote(table), name=quote(index)) is found
    assert probe(editor._sql_constraint_valid, table=quote(table), name=quote(constraint)) is found


NAMES = [
    ("probe_table", "probe_column", "probe_constraint", "probe_index"),
    ("ProbeTable", "ProbeColumn", "ProbeConstraint", "ProbeIndex"),
    ('Probe"Table', 'Probe"Column', 'Probe"Constraint', 'Probe"Index'),
]
NAME_IDS = ["lower case", "mixed case", "quote inside"]


@pytest.mark.parametrize("table, column, constraint, index", NAMES, ids=NAME_IDS)
def test_conditions_find_the_objects(table, column, constraint, index):
    create_table(table, column, constraint, index)

    assert_all_conditions(table, column, constraint, index, found=True)


@pytest.mark.parametrize("table, column, constraint, index", NAMES, ids=NAME_IDS)
def test_conditions_do_not_find_the_objects_that_do_not_exist(table, column, constraint, index):
    assert_all_conditions(table, column, constraint, index, found=False)


@pytest.mark.parametrize("table, column, constraint, index", NAMES, ids=NAME_IDS)
def test_conditions_ignore_the_objects_that_the_search_path_hides(table, column, constraint, index):
    # the same app deployed once per tenant schema keeps the same names in every schema
    create_table(table, column, constraint, index, schema="other_schema")

    assert_all_conditions(table, column, constraint, index, found=False)


def test_the_table_condition_ignores_an_index_of_the_same_name():
    create_table("probe_table", "probe_column", "probe_constraint", "NameCollision")

    assert not probe(DatabaseSchemaEditorMixin._sql_table_exists, table=quote("NameCollision"))
    assert not probe(DatabaseSchemaEditorMixin._sql_new_table_exists, new_table=quote("NameCollision"))


@pytest.mark.parametrize("kind, ddl", [
    ("view", 'CREATE VIEW "NameCollision" AS SELECT 1 AS x'),
    ("materialized view", 'CREATE MATERIALIZED VIEW "NameCollision" AS SELECT 1 AS x'),
])
def test_the_table_condition_ignores_a_relation_that_is_not_a_table(kind, ddl):
    # `CREATE TABLE` and `DROP TABLE` do not act on these, thus they must not answer for a table
    with connection.cursor() as cursor:
        cursor.execute(ddl)

    assert not probe(DatabaseSchemaEditorMixin._sql_table_exists, table=quote("NameCollision"))
    assert not probe(DatabaseSchemaEditorMixin._sql_new_table_exists, new_table=quote("NameCollision"))


def test_the_index_condition_ignores_a_table_of_the_same_name():
    create_table("NameCollision", "probe_column", "probe_constraint", "probe_index")

    assert not probe(DatabaseSchemaEditorMixin._sql_index_exists, name=quote("NameCollision"))
