# Generated by Django 5.0 on 2024-04-22 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("idempotency_create_table_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelatedTestTable",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_field_int", models.IntegerField(null=True)),
                (
                    "test_model",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="idempotency_create_table_app.testtable",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="relatedtesttable",
            constraint=models.UniqueConstraint(
                fields=("test_model", "test_field_int"),
                name="idempotency_create_table_app_relatedtesttable_uniq",
            ),
        ),
    ]
