# Generated by Django 3.1 on 2019-09-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_rollback_flow_change_char_type_that_safe_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtable',
            name='char_filed',
            field=models.CharField(max_length=120),
        ),
    ]
