# Generated by Django 3.1 on 2019-09-22 21:00

from django.db import migrations, models


def insert_objects(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    TestTable = apps.get_model('bad_rollback_flow_drop_column_with_notnull_app', 'TestTable')
    TestTable.objects.using(db_alias).create(field=1)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.IntegerField()),
            ],
        ),
        migrations.RunPython(insert_objects, migrations.RunPython.noop),
    ]
