# Generated by Django 3.1 on 2019-09-22 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bad_rollback_flow_drop_column_with_notnull_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testtable',
            name='field',
        ),
    ]
