name: Build and Publish

on: workflow_dispatch

jobs:
  build-and-publish:
    name: build and publish package
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: set up uv
        uses: astral-sh/setup-uv@v5
      - name: build a binary wheel and a source tarball
        run: uv build
      - name: check distribution metadata
        run: uvx twine check dist/*
      - name: publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
